metadata/force-app/main/default/objects/PDRI__ComparisonView__c/PDRI__ComparisonView__c.object-meta.xml
<CustomObject>
    <label>Comparison View</label>
    <nameField>
        <label>Comparison View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comparison Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/root/main/default/objects/PDRI__ComparisonView__c/fields/PDRI__Default__c.field-meta.xml
<CustomField>
    <fullName>PDRI__Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Default comparison view.</description>
    <inlineHelpText>Default to this comparison view for metadata deployments?</inlineHelpText>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

metadata/force-app/main/default/objects/PDRI__ComparisonView__c/fields/PDRI__Description__c.field-meta.xml
<CustomField>
    <fullName>PDRI__Description__c</fullName>
    <description>Comparison view description.</description>
    <inlineHelpText>Description for the comparison view which</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/root/main/default/objects/PDRI__ComparisonViewRule__c/PDRI__ComparisonViewRule__c.object-meta.xml
<CustomObject>
    <label>Comparison View Rule</label>
    <nameField>
        <displayFormat>CRN-{0000000}</displayFormat>
        <label>Comparison View Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comparison View Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/root/main/default/objects/PDRI__ComparisonViewRule__c/fields/PDRI__ComparisonView__c.field-meta.xml
<CustomField>
    <fullName>PDRI__ComparisonView__c</fullName>
    <description>Action to be taken by this rule.</description>
    <inlineHelpText>What action should this rule take?</inlineHelpText>
    <label>Comparison View</label>
    <referenceTo>PDRI__ComparisonView__c</referenceTo>
    <relationshipName>Comparison_View_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

metadata/force-app/main/default/objects/PDRI__ComparisonViewRule__c/fields/PDRI__ParentRule__c.field-meta.xml
<CustomField>
    <fullName>PDRI__ParentRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Rule</label>
    <referenceTo>PDRI__ComparisonViewRule__c</referenceTo>
    <relationshipLabel>Comparison View Rules</relationshipLabel>
    <relationshipName>Child_Comparison_View_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/root/main/default/classes/MarkCloneComparisonViewController.cls
public with sharing class MarkCloneComparisonViewController {
    @AuraEnabled
    public static String clone(String recordId) {
        PDRI__ComparisonView__c comparisonView =
            [SELECT Name, PDRI__Active__c, PDRI__Default__c, PDRI__Description__c, 
             (SELECT PDRI__Action__c, PDRI__ComparisonView__c, PDRI__FilterType__c, 
            PDRI__FilterValue__c, PDRI__ParentRule__c, PDRI__ParentRuleFilterType__c
            from PDRI__Comparison_View_Rules__r limit 200) from PDRI__ComparisonView__c where Id =:recordId limit 1];
        
        PDRI__ComparisonView__c cloneComparisonView = 
            comparisonView.clone(false, false, false, false);
        
        cloneComparisonView.Name = cloneComparisonView.Name + ' - Clone';
        cloneComparisonView.PDRI__Default__c = false;

        
        insert cloneComparisonView;

        Map<Id,PDRI__ComparisonViewRule__c> comparisonViewRulesMap = 
            new Map<Id,PDRI__ComparisonViewRule__c>();

        List<PDRI__ComparisonViewRule__c> cloneParentComparisonViewRules =
            new List<PDRI__ComparisonViewRule__c>();
        
        List<PDRI__ComparisonViewRule__c> cloneChildComparisonViewRules =
            new List<PDRI__ComparisonViewRule__c>();

        for( PDRI__ComparisonViewRule__c comparisonViewRule : comparisonView.PDRI__Comparison_View_Rules__r ) {
            PDRI__ComparisonViewRule__c cloneComparisonViewRule = 
                comparisonViewRule.clone(false, false, false, false);
            
            cloneComparisonViewRule.PDRI__ComparisonView__c = cloneComparisonView.Id;

            if( cloneComparisonViewRule.PDRI__ParentRule__c != null ) {
                cloneChildComparisonViewRules.add(cloneComparisonViewRule); 
            } else {
                cloneParentComparisonViewRules.add(cloneComparisonViewRule);  
                comparisonViewRulesMap.put(comparisonViewRule.Id, cloneComparisonViewRule);
            }    
        }

        insert cloneParentComparisonViewRules;

        for( PDRI__ComparisonViewRule__c cloneComparisonViewRule : cloneChildComparisonViewRules ) {
            PDRI__ComparisonViewRule__c parentRule = comparisonViewRulesMap.get( cloneComparisonViewRule.PDRI__ParentRule__c );
            
            if( parentRule == null ) {
                continue;
            }
            cloneComparisonViewRule.PDRI__ParentRule__c = parentRule.Id;
        }

        insert cloneChildComparisonViewRules;

        return cloneComparisonView.Id;
    }
}